SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS employee (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    department VARCHAR(100) NOT NULL,
    role VARCHAR(100) NOT NULL,
    hire_date DATE,
    is_public_calendar TINYINT DEFAULT 1,
    phone VARCHAR(30) COMMENT '手机号'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS calendar_event (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    event_type VARCHAR(50) NOT NULL COMMENT 'LEAVE:请假, ONBOARDING:入职, ANNIVERSARY:司龄, DEPT_ACTIVITY:部门活动, HOLIDAY:节假日, INTERVIEW:面试, CUSTOM:自定义',
    start_time DATETIME NOT NULL,
    end_time DATETIME NOT NULL,
    is_all_day TINYINT DEFAULT 0,
    color VARCHAR(20),
    location VARCHAR(500),
    employee_id BIGINT,
    employee_name VARCHAR(100),
    department VARCHAR(100),
    source_module VARCHAR(50) COMMENT '来源模块：LEAVE, HR, ACTIVITY, HOLIDAY, INTERVIEW, CUSTOM',
    source_id VARCHAR(100) COMMENT '来源模块中的记录ID',
    is_public TINYINT DEFAULT 1 COMMENT '是否公开可见',
    created_by BIGINT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_time_range (start_time, end_time),
    INDEX idx_event_type (event_type),
    INDEX idx_employee (employee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS calendar_subscription (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    subscriber_id BIGINT NOT NULL,
    subscriber_name VARCHAR(100) NOT NULL,
    target_employee_id BIGINT NOT NULL,
    target_employee_name VARCHAR(100) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_subscription (subscriber_id, target_employee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS performance_batch (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    batch_name VARCHAR(200) NOT NULL COMMENT '评估批次名称',
    cycle_type VARCHAR(20) NOT NULL COMMENT 'QUARTERLY:季度, SEMI_ANNUAL:半年度, ANNUAL:年度',
    cycle_year INT NOT NULL COMMENT '评估年度',
    cycle_quarter INT COMMENT '季度 1-4，仅季度评估使用',
    department VARCHAR(100) COMMENT '部门，为空表示全公司',
    start_date DATE NOT NULL COMMENT '评估周期开始日期',
    end_date DATE NOT NULL COMMENT '评估周期结束日期',
    self_eval_deadline DATETIME COMMENT '自评截止时间',
    manager_review_deadline DATETIME COMMENT '主管评分截止时间',
    hr_review_deadline DATETIME COMMENT 'HR复核截止时间',
    status VARCHAR(30) NOT NULL DEFAULT 'SELF_EVALUATION' COMMENT 'SELF_EVALUATION, MANAGER_REVIEW, HR_REVIEW, CONFIRMED, ARCHIVED',
    description TEXT COMMENT '评估说明',
    created_by BIGINT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_cycle (cycle_year, cycle_type),
    INDEX idx_department (department),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS performance_evaluation (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    employee_name VARCHAR(100) NOT NULL,
    department VARCHAR(100),
    manager_id BIGINT COMMENT '主管ID',
    manager_name VARCHAR(100) COMMENT '主管姓名',
    stage VARCHAR(30) NOT NULL DEFAULT 'SELF_EVALUATION' COMMENT 'SELF_EVALUATION, MANAGER_REVIEW, HR_REVIEW, CONFIRMED, ARCHIVED',
    self_score DECIMAL(5,2) COMMENT '自评分',
    self_comment TEXT COMMENT '自评评语',
    self_submitted_at DATETIME COMMENT '自评提交时间',
    manager_score DECIMAL(5,2) COMMENT '主管评分',
    final_grade VARCHAR(5) COMMENT 'S/A/B/C/D',
    manager_comment TEXT COMMENT '主管评语',
    improvement_plan TEXT COMMENT '改进计划',
    manager_submitted_at DATETIME COMMENT '主管提交时间',
    hr_comment TEXT COMMENT 'HR复核意见',
    hr_reviewed_at DATETIME COMMENT 'HR复核时间',
    salary_adjustment_suggestion VARCHAR(500) COMMENT '薪资调薪建议',
    confirmed_at DATETIME COMMENT '结果确认时间',
    is_locked TINYINT DEFAULT 0 COMMENT '是否已锁定归档',
    rank_in_dept INT COMMENT '部门内排名',
    potential_rating VARCHAR(20) COMMENT '潜力评级: LOW/MEDIUM/HIGH',
    performance_rating VARCHAR(20) COMMENT '绩效评级: LOW/MEDIUM/HIGH',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_batch (batch_id),
    INDEX idx_employee (employee_id),
    INDEX idx_department (department),
    INDEX idx_stage (stage),
    INDEX idx_grade (final_grade)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS performance_dimension_config (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    dimension_name VARCHAR(100) NOT NULL COMMENT '维度名称',
    dimension_code VARCHAR(50) NOT NULL UNIQUE COMMENT '维度编码',
    description TEXT COMMENT '维度说明',
    weight DECIMAL(5,2) COMMENT '权重',
    max_score DECIMAL(5,2) DEFAULT 100 COMMENT '最高分',
    is_active TINYINT DEFAULT 1 COMMENT '是否启用',
    sort_order INT DEFAULT 0 COMMENT '排序',
    INDEX idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS performance_dimension_score (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    evaluation_id BIGINT NOT NULL,
    dimension_name VARCHAR(100) NOT NULL,
    dimension_code VARCHAR(50) NOT NULL,
    weight DECIMAL(5,2) COMMENT '权重',
    self_score DECIMAL(5,2) COMMENT '自评分',
    manager_score DECIMAL(5,2) COMMENT '主管评分',
    self_comment TEXT COMMENT '自评说明',
    manager_comment TEXT COMMENT '主管评分说明',
    INDEX idx_evaluation (evaluation_id),
    INDEX idx_dimension (dimension_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS performance_appeal (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    evaluation_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    employee_name VARCHAR(100) NOT NULL,
    appeal_reason VARCHAR(500) NOT NULL COMMENT '申诉原因',
    appeal_detail TEXT COMMENT '申诉详情',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING, APPROVED, REJECTED, CANCELLED',
    reviewer_id BIGINT COMMENT '审核人ID',
    reviewer_name VARCHAR(100) COMMENT '审核人姓名',
    review_comment TEXT COMMENT '审核意见',
    reviewed_at DATETIME COMMENT '审核时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_evaluation (evaluation_id),
    INDEX idx_employee (employee_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS calibration_meeting (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    department VARCHAR(100),
    meeting_name VARCHAR(200) NOT NULL,
    meeting_date DATETIME,
    participants TEXT COMMENT '参会人员',
    meeting_notes TEXT COMMENT '会议纪要',
    created_by BIGINT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_batch (batch_id),
    INDEX idx_department (department)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS calibration_adjustment (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    meeting_id BIGINT NOT NULL,
    evaluation_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    employee_name VARCHAR(100) NOT NULL,
    original_grade VARCHAR(5) COMMENT '校准前等级',
    original_score DECIMAL(5,2) COMMENT '校准前分数',
    original_rank INT COMMENT '校准前排名',
    adjusted_grade VARCHAR(5) COMMENT '校准后等级',
    adjusted_score DECIMAL(5,2) COMMENT '校准后分数',
    adjusted_rank INT COMMENT '校准后排名',
    adjustment_reason TEXT COMMENT '调整原因',
    adjusted_by BIGINT COMMENT '调整人',
    adjusted_at DATETIME COMMENT '调整时间',
    INDEX idx_meeting (meeting_id),
    INDEX idx_evaluation (evaluation_id),
    INDEX idx_employee (employee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS skill_tag (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tag_name VARCHAR(100) NOT NULL COMMENT '标签名称',
    category VARCHAR(50) NOT NULL COMMENT 'LANGUAGE:编程语言, FRAMEWORK:框架工具, SOFT_SKILL:软技能, CERTIFICATE:专业证书, DATABASE:数据库, DEVOPS:运维部署, OTHER:其他',
    description TEXT COMMENT '标签说明',
    heat_weight DECIMAL(10,2) DEFAULT 0 COMMENT '热度权重',
    validation_cycle_days INT DEFAULT 365 COMMENT '验证周期(天)',
    is_active TINYINT DEFAULT 1 COMMENT '是否启用',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_tag_name (tag_name),
    INDEX idx_category (category),
    INDEX idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS employee_skill (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    employee_name VARCHAR(100),
    department VARCHAR(100),
    skill_tag_id BIGINT NOT NULL,
    skill_tag_name VARCHAR(100),
    category VARCHAR(50),
    proficiency INT NOT NULL COMMENT '1:入门, 2:初级, 3:中级, 4:高级, 5:专家',
    last_verified_date DATE COMMENT '最后验证日期',
    is_expired TINYINT DEFAULT 0 COMMENT '是否过期',
    evidence TEXT COMMENT '证明材料/备注',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_employee_skill (employee_id, skill_tag_id),
    INDEX idx_employee (employee_id),
    INDEX idx_skill_tag (skill_tag_id),
    INDEX idx_department (department),
    INDEX idx_proficiency (proficiency),
    INDEX idx_expired (is_expired)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS skill_alias (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    alias_name VARCHAR(100) NOT NULL COMMENT '别名',
    primary_tag_id BIGINT NOT NULL COMMENT '主标签ID',
    primary_tag_name VARCHAR(100) COMMENT '主标签名称',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_alias_name (alias_name),
    INDEX idx_primary_tag (primary_tag_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS skill_change_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    employee_name VARCHAR(100),
    skill_tag_id BIGINT NOT NULL,
    skill_tag_name VARCHAR(100),
    change_type VARCHAR(20) NOT NULL COMMENT 'ADD:新增, UPDATE:更新, REMOVE:移除',
    old_proficiency INT COMMENT '变更前熟练度',
    new_proficiency INT COMMENT '变更后熟练度',
    old_last_verified_date DATE COMMENT '变更前验证日期',
    new_last_verified_date DATE COMMENT '变更后验证日期',
    change_reason VARCHAR(500) COMMENT '变更原因',
    operator_id BIGINT COMMENT '操作人ID',
    operator_name VARCHAR(100) COMMENT '操作人姓名',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_employee (employee_id),
    INDEX idx_skill_tag (skill_tag_id),
    INDEX idx_change_type (change_type),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS attachment_category (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    category_code VARCHAR(50) NOT NULL UNIQUE COMMENT '分类编码: LABOR_CONTRACT, ID_CARD, EDUCATION, CERTIFICATE, OTHER',
    category_name VARCHAR(100) NOT NULL COMMENT '分类名称: 劳动合同, 身份证, 学历证明, 证书, 其他',
    description TEXT COMMENT '分类说明',
    sort_order INT DEFAULT 0 COMMENT '排序',
    is_active TINYINT DEFAULT 1 COMMENT '是否启用',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS employee_attachment (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT NOT NULL COMMENT '员工ID',
    employee_name VARCHAR(100) COMMENT '员工姓名',
    department VARCHAR(100) COMMENT '所属部门',
    attachment_group_id VARCHAR(64) NOT NULL COMMENT '附件组ID(同一分类同一员工的不同版本共用)',
    category_id BIGINT NOT NULL COMMENT '分类ID',
    category_code VARCHAR(50) NOT NULL COMMENT '分类编码(冗余)',
    category_name VARCHAR(100) COMMENT '分类名称(冗余)',
    file_name VARCHAR(255) NOT NULL COMMENT '文件原始名称',
    stored_file_name VARCHAR(255) NOT NULL COMMENT '存储文件名(UUID)',
    file_path VARCHAR(500) NOT NULL COMMENT '文件存储路径',
    file_size BIGINT NOT NULL COMMENT '文件大小(字节)',
    mime_type VARCHAR(100) NOT NULL COMMENT 'MIME类型',
    file_extension VARCHAR(20) COMMENT '文件扩展名',
    version INT NOT NULL DEFAULT 1 COMMENT '版本号',
    is_latest TINYINT DEFAULT 1 COMMENT '是否为最新版本',
    expire_date DATE COMMENT '有效期截止日期',
    is_expired TINYINT DEFAULT 0 COMMENT '是否已过期',
    expiry_reminder_sent TINYINT DEFAULT 0 COMMENT '是否已发送到期提醒',
    uploader_id BIGINT COMMENT '上传人ID',
    uploader_name VARCHAR(100) COMMENT '上传人姓名',
    uploaded_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '上传时间',
    description TEXT COMMENT '附件说明/备注',
    is_deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记',
    deleted_at DATETIME COMMENT '删除时间',
    deleted_by BIGINT COMMENT '删除人ID',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_employee (employee_id),
    INDEX idx_category (category_id),
    INDEX idx_group (attachment_group_id),
    INDEX idx_expire (expire_date),
    INDEX idx_uploader (uploader_id),
    INDEX idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS employee_storage_quota (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT NOT NULL UNIQUE COMMENT '员工ID',
    employee_name VARCHAR(100),
    total_quota_bytes BIGINT NOT NULL DEFAULT 524288000 COMMENT '总配额(字节), 默认500MB',
    used_bytes BIGINT NOT NULL DEFAULT 0 COMMENT '已使用空间(字节)',
    max_single_file_bytes BIGINT NOT NULL DEFAULT 52428800 COMMENT '单文件最大限制(字节), 默认50MB',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_employee (employee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_message (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT NOT NULL COMMENT '员工ID',
    employee_name VARCHAR(100) COMMENT '员工姓名',
    event_type VARCHAR(50) NOT NULL COMMENT 'APPROVAL_FLOW,ANNOUNCEMENT,CONTRACT_EXPIRY,ONBOARDING_OVERDUE,ATTENDANCE_ABNORMAL,SALARY_PAID,PERFORMANCE_REMIND,ATTACHMENT_EXPIRY,SYSTEM',
    title VARCHAR(200) NOT NULL COMMENT '消息标题',
    summary VARCHAR(500) COMMENT '消息摘要',
    biz_type VARCHAR(50) COMMENT '关联业务类型',
    biz_id VARCHAR(100) COMMENT '关联业务ID',
    deep_link VARCHAR(500) COMMENT '跳转深链',
    is_read TINYINT DEFAULT 0 COMMENT '是否已读',
    read_at DATETIME COMMENT '阅读时间',
    is_archived TINYINT DEFAULT 0 COMMENT '是否已归档',
    archived_at DATETIME COMMENT '归档时间',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX idx_employee (employee_id),
    INDEX idx_event_type (event_type),
    INDEX idx_is_read (is_read),
    INDEX idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS message_preference (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT NOT NULL COMMENT '员工ID',
    event_type VARCHAR(50) NOT NULL COMMENT '消息事件类型',
    push_enabled TINYINT DEFAULT 1 COMMENT '是否开启推送',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_emp_event (employee_id, event_type),
    INDEX idx_employee (employee_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_config (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    config_group VARCHAR(50) NOT NULL COMMENT '配置分组: COMPANY_INFO, BUSINESS_RULES, SECURITY_POLICY, FEATURE_TOGGLE',
    config_key VARCHAR(100) NOT NULL COMMENT '配置键',
    config_value TEXT COMMENT '配置值',
    value_type VARCHAR(20) NOT NULL DEFAULT 'STRING' COMMENT '值类型: STRING, INTEGER, BOOLEAN, NUMBER',
    display_name VARCHAR(100) NOT NULL COMMENT '显示名称',
    description VARCHAR(500) COMMENT '配置说明',
    sort_order INT DEFAULT 0 COMMENT '排序',
    updated_by VARCHAR(100) COMMENT '最后修改人',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_group_key (config_group, config_key),
    INDEX idx_group (config_group),
    INDEX idx_key (config_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_config_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    config_group VARCHAR(50) NOT NULL COMMENT '配置分组',
    config_key VARCHAR(100) NOT NULL COMMENT '配置键',
    display_name VARCHAR(100) COMMENT '显示名称',
    old_value TEXT COMMENT '变更前值',
    new_value TEXT COMMENT '变更后值',
    changed_by VARCHAR(100) NOT NULL COMMENT '变更人',
    changed_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '变更时间',
    INDEX idx_group (config_group),
    INDEX idx_key (config_key),
    INDEX idx_changed_at (changed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS employee_contract (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    contract_no VARCHAR(50) NOT NULL UNIQUE COMMENT '合同编号',
    employee_id BIGINT NOT NULL COMMENT '员工ID',
    employee_name VARCHAR(100) COMMENT '员工姓名',
    department VARCHAR(100) COMMENT '所属部门',
    contract_type VARCHAR(30) NOT NULL COMMENT '合同类型: FIXED_TERM:固定期限, OPEN_ENDED:无固定期限, INTERNSHIP:实习, LABOR_SERVICE:劳务',
    start_date DATE NOT NULL COMMENT '合同开始日期',
    end_date DATE COMMENT '合同结束日期(无固定期限可为空)',
    probation_start_date DATE COMMENT '试用期开始日期',
    probation_end_date DATE COMMENT '试用期结束日期',
    probation_salary_ratio DECIMAL(5,2) COMMENT '试用期薪资比例(如0.8表示80%)',
    contract_status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' COMMENT '签约状态: DRAFT:草稿, ACTIVE:生效, EXPIRED:到期, TERMINATED:终止, RENEWING:续签中',
    sign_status VARCHAR(30) NOT NULL DEFAULT 'PENDING' COMMENT '电子签署状态: PENDING:待签, SIGNED:已签, REJECTED:拒签',
    signed_date DATE COMMENT '签署日期',
    reject_reason VARCHAR(500) COMMENT '拒签原因',
    previous_contract_id BIGINT COMMENT '前序合同ID,用于续签关联形成链条',
    termination_reason VARCHAR(500) COMMENT '终止原因',
    termination_date DATE COMMENT '终止日期',
    termination_operator_id BIGINT COMMENT '终止操作人ID',
    termination_operator_name VARCHAR(100) COMMENT '终止操作人姓名',
    is_offboarding_triggered TINYINT DEFAULT 0 COMMENT '是否已触发离职流程',
    warning_30d_sent TINYINT DEFAULT 0 COMMENT '30天到期预警是否已发送',
    warning_15d_sent TINYINT DEFAULT 0 COMMENT '15天到期预警是否已发送',
    warning_7d_sent TINYINT DEFAULT 0 COMMENT '7天到期预警是否已发送',
    remark TEXT COMMENT '备注',
    created_by BIGINT COMMENT '创建人ID',
    created_by_name VARCHAR(100) COMMENT '创建人姓名',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_employee (employee_id),
    INDEX idx_contract_type (contract_type),
    INDEX idx_contract_status (contract_status),
    INDEX idx_sign_status (sign_status),
    INDEX idx_start_date (start_date),
    INDEX idx_end_date (end_date),
    INDEX idx_previous (previous_contract_id),
    INDEX idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS candidate (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL COMMENT '姓名',
    phone VARCHAR(30) COMMENT '联系电话',
    email VARCHAR(100) COMMENT '邮箱',
    applied_position VARCHAR(100) COMMENT '应聘职位',
    department VARCHAR(100) COMMENT '应聘部门',
    source_channel VARCHAR(30) COMMENT '来源渠道: INTERNAL_REFERRAL, RECRUITMENT_WEBSITE, SOCIAL_MEDIA, CAMPUS_RECRUITMENT, HEADHUNTER, DIRECT_APPLICATION, OTHER',
    expected_salary_min DECIMAL(12,2) COMMENT '期望薪资最低',
    expected_salary_max DECIMAL(12,2) COMMENT '期望薪资最高',
    resume_attachment_id BIGINT COMMENT '简历附件ID',
    resume_attachment_name VARCHAR(255) COMMENT '简历附件名称',
    referrer_id BIGINT COMMENT '内推人ID',
    referrer_name VARCHAR(100) COMMENT '内推人姓名',
    stage VARCHAR(30) NOT NULL DEFAULT 'RESUME_SCREENING' COMMENT '当前阶段: RESUME_SCREENING, WRITTEN_TEST, FIRST_INTERVIEW, SECOND_INTERVIEW, HR_INTERVIEW, OFFER_APPROVAL, HIRED, ELIMINATED',
    is_in_talent_pool TINYINT DEFAULT 0 COMMENT '是否在人才库',
    eliminate_reason VARCHAR(500) COMMENT '淘汰原因',
    eliminate_time DATETIME COMMENT '淘汰时间',
    offer_salary DECIMAL(12,2) COMMENT 'Offer薪资',
    offer_start_date DATE COMMENT 'Offer入职日期',
    offer_approval_status VARCHAR(20) COMMENT 'Offer审批状态: PENDING, APPROVED, REJECTED',
    offer_approver_id BIGINT COMMENT 'Offer审批人ID',
    offer_approver_name VARCHAR(100) COMMENT 'Offer审批人姓名',
    offer_approval_time DATETIME COMMENT 'Offer审批时间',
    converted_employee_id BIGINT COMMENT '转化后的员工ID',
    created_by BIGINT COMMENT '创建人ID',
    created_by_name VARCHAR(100) COMMENT '创建人姓名',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    remark TEXT COMMENT '备注',
    INDEX idx_name (name),
    INDEX idx_stage (stage),
    INDEX idx_source (source_channel),
    INDEX idx_position (applied_position),
    INDEX idx_department (department),
    INDEX idx_talent_pool (is_in_talent_pool),
    INDEX idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS interview_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    candidate_id BIGINT NOT NULL COMMENT '候选人ID',
    candidate_name VARCHAR(100) COMMENT '候选人姓名',
    interview_round VARCHAR(30) NOT NULL COMMENT '面试轮次: WRITTEN_TEST, FIRST_INTERVIEW, SECOND_INTERVIEW, HR_INTERVIEW',
    interviewer_id BIGINT COMMENT '面试官ID',
    interviewer_name VARCHAR(100) COMMENT '面试官姓名',
    interview_time DATETIME COMMENT '面试时间',
    score DECIMAL(5,2) COMMENT '评分',
    evaluation TEXT COMMENT '评价',
    is_passed TINYINT COMMENT '是否通过',
    created_by BIGINT COMMENT '创建人ID',
    created_by_name VARCHAR(100) COMMENT '创建人姓名',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    remark TEXT COMMENT '备注',
    INDEX idx_candidate (candidate_id),
    INDEX idx_round (interview_round),
    INDEX idx_interviewer (interviewer_id),
    INDEX idx_time (interview_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS stage_transition_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    candidate_id BIGINT NOT NULL COMMENT '候选人ID',
    candidate_name VARCHAR(100) COMMENT '候选人姓名',
    from_stage VARCHAR(30) COMMENT '原阶段',
    to_stage VARCHAR(30) NOT NULL COMMENT '目标阶段',
    operator_id BIGINT COMMENT '操作人ID',
    operator_name VARCHAR(100) COMMENT '操作人姓名',
    transition_reason VARCHAR(500) COMMENT '流转原因',
    transition_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '流转时间',
    remark TEXT COMMENT '备注',
    INDEX idx_candidate (candidate_id),
    INDEX idx_from_stage (from_stage),
    INDEX idx_to_stage (to_stage),
    INDEX idx_operator (operator_id),
    INDEX idx_transition_time (transition_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS shift_definition (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    shift_code VARCHAR(50) NOT NULL COMMENT '班次编码: MORNING/EVENING/NIGHT_SHIFT/REST/CUSTOM',
    shift_name VARCHAR(100) NOT NULL COMMENT '班次名称: 早班/晚班/大夜班/休息/自定义',
    department VARCHAR(100) NOT NULL COMMENT '所属部门',
    start_time TIME NOT NULL COMMENT '班次开始时间',
    end_time TIME NOT NULL COMMENT '班次结束时间',
    is_cross_day TINYINT DEFAULT 0 COMMENT '是否跨天: 0-否, 1-是',
    color VARCHAR(20) DEFAULT '#1890FF' COMMENT '班次显示颜色',
    sort_order INT DEFAULT 0 COMMENT '排序',
    is_active TINYINT DEFAULT 1 COMMENT '是否启用',
    description VARCHAR(500) COMMENT '备注说明',
    created_by BIGINT COMMENT '创建人ID',
    created_by_name VARCHAR(100) COMMENT '创建人姓名',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_dept_shift (department, shift_code),
    INDEX idx_department (department),
    INDEX idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS employee_schedule (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    schedule_week VARCHAR(20) NOT NULL COMMENT '排班周标识: YYYY-WW 如 2026-23',
    department VARCHAR(100) NOT NULL COMMENT '所属部门',
    employee_id BIGINT NOT NULL COMMENT '员工ID',
    employee_name VARCHAR(100) NOT NULL COMMENT '员工姓名',
    team_group VARCHAR(100) COMMENT '班组',
    schedule_date DATE NOT NULL COMMENT '排班日期',
    shift_id BIGINT NOT NULL COMMENT '班次定义ID',
    shift_code VARCHAR(50) NOT NULL COMMENT '班次编码',
    shift_name VARCHAR(100) NOT NULL COMMENT '班次名称',
    start_time TIME COMMENT '实际开始时间(覆盖默认)',
    end_time TIME COMMENT '实际结束时间(覆盖默认)',
    is_cross_day TINYINT DEFAULT 0 COMMENT '是否跨天',
    effective_start_date DATE COMMENT '生效开始日期',
    effective_end_date DATE COMMENT '生效结束日期',
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' COMMENT '状态: DRAFT-草稿, CONFIRMED-已确认, LOCKED-已锁定',
    confirmed_by BIGINT COMMENT '确认人ID',
    confirmed_by_name VARCHAR(100) COMMENT '确认人姓名',
    confirmed_at DATETIME COMMENT '确认时间',
    remark VARCHAR(500) COMMENT '备注',
    created_by BIGINT COMMENT '创建人ID',
    created_by_name VARCHAR(100) COMMENT '创建人姓名',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_emp_date (employee_id, schedule_date),
    INDEX idx_week_dept (schedule_week, department),
    INDEX idx_employee (employee_id),
    INDEX idx_date (schedule_date),
    INDEX idx_status (status),
    INDEX idx_team (team_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS schedule_change_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    schedule_id BIGINT COMMENT '关联排班记录ID',
    employee_id BIGINT NOT NULL COMMENT '员工ID',
    employee_name VARCHAR(100) NOT NULL COMMENT '员工姓名',
    schedule_date DATE NOT NULL COMMENT '排班日期',
    change_type VARCHAR(30) NOT NULL COMMENT '变更类型: CREATE-新增, UPDATE-修改, DELETE-删除, BATCH_UPDATE-批量更新, COPY-复制',
    old_shift_id BIGINT COMMENT '原班次ID',
    old_shift_code VARCHAR(50) COMMENT '原班次编码',
    old_shift_name VARCHAR(100) COMMENT '原班次名称',
    new_shift_id BIGINT COMMENT '新班次ID',
    new_shift_code VARCHAR(50) COMMENT '新班次编码',
    new_shift_name VARCHAR(100) COMMENT '新班次名称',
    change_reason VARCHAR(500) NOT NULL COMMENT '变更原因',
    operator_id BIGINT NOT NULL COMMENT '操作人ID',
    operator_name VARCHAR(100) NOT NULL COMMENT '操作人姓名',
    changed_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '变更时间',
    INDEX idx_schedule (schedule_id),
    INDEX idx_employee (employee_id),
    INDEX idx_date (schedule_date),
    INDEX idx_operator (operator_id),
    INDEX idx_changed_at (changed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS attendance_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT NOT NULL COMMENT '员工ID',
    employee_name VARCHAR(100) NOT NULL COMMENT '员工姓名',
    department VARCHAR(100) COMMENT '所属部门',
    attendance_date DATE NOT NULL COMMENT '考勤日期',
    schedule_id BIGINT COMMENT '关联排班ID',
    shift_id BIGINT COMMENT '班次ID',
    shift_code VARCHAR(50) COMMENT '班次编码',
    punch_in_time DATETIME COMMENT '上班打卡时间',
    punch_out_time DATETIME COMMENT '下班打卡时间',
    work_hours DECIMAL(5,2) COMMENT '实际工作时长(小时)',
    is_late TINYINT DEFAULT 0 COMMENT '是否迟到',
    late_minutes INT DEFAULT 0 COMMENT '迟到分钟数',
    is_early_leave TINYINT DEFAULT 0 COMMENT '是否早退',
    early_leave_minutes INT DEFAULT 0 COMMENT '早退分钟数',
    is_absent TINYINT DEFAULT 0 COMMENT '是否旷工',
    is_abnormal TINYINT DEFAULT 0 COMMENT '是否异常',
    abnormal_type VARCHAR(50) COMMENT '异常类型: LATE-迟到, EARLY_LEAVE-早退, ABSENT-旷工, MISSING_PUNCH-缺卡, LEAVE-请假, OVERTIME-加班',
    abnormal_reason VARCHAR(500) COMMENT '异常说明',
    remark VARCHAR(500) COMMENT '备注',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_emp_date (employee_id, attendance_date),
    INDEX idx_date_dept (attendance_date, department),
    INDEX idx_employee (employee_id),
    INDEX idx_abnormal (is_abnormal)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS schedule_alert (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    alert_type VARCHAR(50) NOT NULL COMMENT '告警类型: MULTI_SHIFT-同日多班次, CONSECUTIVE_NIGHT-连续大夜班超限, REST_INTERVAL-休息间隔不足',
    severity VARCHAR(20) NOT NULL DEFAULT 'WARNING' COMMENT '严重级别: INFO-提示, WARNING-警告, ERROR-错误',
    department VARCHAR(100) COMMENT '所属部门',
    employee_id BIGINT NOT NULL COMMENT '员工ID',
    employee_name VARCHAR(100) NOT NULL COMMENT '员工姓名',
    alert_date DATE COMMENT '告警日期',
    alert_start_date DATE COMMENT '告警开始日期(范围)',
    alert_end_date DATE COMMENT '告警结束日期(范围)',
    message VARCHAR(500) NOT NULL COMMENT '告警信息',
    detail TEXT COMMENT '详细信息(JSON)',
    is_resolved TINYINT DEFAULT 0 COMMENT '是否已处理',
    resolved_by BIGINT COMMENT '处理人ID',
    resolved_by_name VARCHAR(100) COMMENT '处理人姓名',
    resolved_at DATETIME COMMENT '处理时间',
    resolve_note VARCHAR(500) COMMENT '处理备注',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_type (alert_type),
    INDEX idx_employee (employee_id),
    INDEX idx_date (alert_date),
    INDEX idx_resolved (is_resolved),
    INDEX idx_dept (department)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT,
    employee_name VARCHAR(100),
    operation_type VARCHAR(50) NOT NULL,
    operation_module VARCHAR(50),
    operation_detail TEXT,
    target_id VARCHAR(100),
    ip_address VARCHAR(50),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_employee (employee_id),
    INDEX idx_operation_type (operation_type),
    INDEX idx_module (operation_module),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS import_task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_id VARCHAR(64) NOT NULL UNIQUE,
    task_type VARCHAR(30) NOT NULL,
    file_name VARCHAR(255),
    total_count INT DEFAULT 0,
    success_count INT DEFAULT 0,
    failed_count INT DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    error_message TEXT,
    created_by BIGINT,
    created_by_name VARCHAR(100),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_task_id (task_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
